name: Update Calendar

on:
  schedule:
    - cron: '0 0 * * *'  # Это обновит каждый день
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Update Contribution Snake
        uses: Platane/snk@v2
        with:
          github_user: 'Trofim-programming'
          file_name: 'assets/github-contribution-grid-snake.svg'
      - name: Commit and push changes
        run: |
          git config --global user.name "Trofim-programming"
          git config --global user.email "trofimzivilik14@gmail.com"
          git add .
          git commit -m "Update contribution calendar"
          git push

