name: 🤖 Issue Bot

on:
  issues:
    types: [opened]

jobs:
  bot_reply:
    runs-on: ubuntu-latest
    steps:
      - name: 💬 Ответ на новый Issue
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = context.payload.issue;
            const author = issue.user.login;
            const message = `Привет, @${author}! 👋 Спасибо за твой Issue. Наши разработчики скоро ответят! 🚀`;

            github.rest.issues.createComment({
              issue_number: issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });


