name: 🤖 Чат-бот

on:
  push:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Клонируем репозиторий
        uses: actions/checkout@v3

      - name: 🐍 Устанавливаем Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: 📦 Устанавливаем зависимости
        run: pip install -r requirements.txt || echo "Нет зависимостей"

      - name: 🚀 Запускаем бота
        run: python bot.py



